### ISSUE TITLE
DocuWiki Hogfather Version Compatibility?

### ISSUE THREAD

**Issue by GameDoc-MS** [danny0838/dokuwiki-plugin-editx#14]
Is this plugin compatible with the DocuWiki Hogfather Version?
THX

**Comment by danny0838** [comment]
As mentioned in the [plugin page](https://www.dokuwiki.org/plugin:editx), we have stopped development on this for a long time. I cannot test it now as I am not using PHP and DokuWiki, but I'd assume it be not compatible with PHP 7. You can simply try by yourself for verification.
